name: Continuous
on: push
jobs:
  test-and-build:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: '1.13'
      - name: Check code format
        run: |
          UNFORMATED=$(gofmt -l ./)
          COUNT=$(echo $UNFORMATED | wc -w)
          if [ $COUNT -eq 0 ]; then
              echo "Files formatted properly!"
              exit 0
          fi
          echo "The following files are not properly formatted:"
          echo >&2 $UNFORMATED
          exit 1
      - name: Run tests
        run: make test
